#!/usr/bin/env python3
"""Build a versioned resume from YAML; paths are relative to this script, not cwd."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import time
from urllib.parse import quote

try:
    import yaml
    from jinja2 import Environment, FileSystemLoader, StrictUndefined, TemplateError
    from jsonschema import Draft202012Validator, FormatChecker
    from jsonschema.exceptions import SchemaError
except ImportError as exc:
    raise SystemExit(f"Missing Python dependency: {exc.name}. Install resume/requirements.txt with your Python interpreter.") from exc

ROOT = Path(__file__).resolve().parents[2]
SECTION_ORDER = ('profile', 'skills', 'experience', 'projects', 'education', 'interests')
SCHEMA_VERSION = '1.0.0'
GENERATED = 'GENERATED by resume/scripts/build_resume.py; edit content/*.yaml, not this file.'
MONTHS = ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
TEX_ESCAPES = {'\\': r'\textbackslash{}', '&': r'\&', '%': r'\%', '$': r'\$', '#': r'\#',
               '_': r'\_', '{': r'\{', '}': r'\}', '~': r'\textasciitilde{}', '^': r'\textasciicircum{}'}


class BuildError(Exception):
    """An actionable source, validation, rendering or compiler error."""


class UniqueKeyLoader(yaml.SafeLoader):
    """Do not silently overwrite a YAML mapping's repeated keys."""


def unique_mapping(loader, node, deep=False):
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if not isinstance(key, str):
            raise BuildError(f"YAML mapping keys must be strings (line {key_node.start_mark.line + 1}).")
        if key in result:
            raise BuildError(f"Duplicate YAML key {key!r} (line {key_node.start_mark.line + 1}).")
        result[key] = loader.construct_object(value_node, deep=deep)
    return result


UniqueKeyLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def read_yaml(path):
    try:
        return yaml.load(path.read_text(encoding='utf-8'), Loader=UniqueKeyLoader)
    except (OSError, yaml.YAMLError, BuildError) as exc:
        raise BuildError(f"{path}: {exc}") from exc


def tex_escape(value):
    """Escape once, character by character, so inserted commands are never re-escaped."""
    return ''.join(TEX_ESCAPES.get(char, char) for char in str(value))


def url_escape(value):
    """Preserve URI delimiters; encode unsafe characters, then protect TeX's tokens."""
    encoded = quote(value, safe=":/?#[]@!$&'()*+,;=%~-._")
    return ''.join({'%': r'\%', '#': r'\#', '&': r'\&', '$': r'\$', '_': r'\_'}.get(c, c) for c in encoded)


def keep_words(value, words):
    """Apply the template's nonbreaking word choices after escaping."""
    pattern = r'(?<![\w])(?:' + '|'.join(re.escape(word) for word in words) + r')(?![\w])'
    return re.sub(pattern, lambda match: r'\mbox{' + match[0] + '}', value) if words else value


def date_range(entry):
    def display(value):
        year, month = value.split('-')
        return f'{MONTHS[int(month) - 1]} {year}'
    if entry['startDate'] is None:
        return display(entry['endDate']) if entry['endDate'] else ''
    return f"{display(entry['startDate'])} - {display(entry['endDate']) if entry['endDate'] else 'Present'}"


def validation_errors(data, schema, label):
    errors = sorted(Draft202012Validator(schema, format_checker=FormatChecker()).iter_errors(data),
                    key=lambda error: '.'.join(map(str, error.absolute_path)))
    if errors:
        details = '\n'.join(f"  {label}.{'.'.join(map(str, e.absolute_path)) or '<root>'}: {e.message}" for e in errors)
        raise BuildError(f'Schema validation failed:\n{details}')


def load_and_validate(root=ROOT):
    try:
        schema = json.loads((root / 'resume' / 'resume.schema.json').read_text(encoding='utf-8'))
        Draft202012Validator.check_schema(schema)
    except (OSError, ValueError, SchemaError) as exc:
        raise BuildError(f'resume/resume.schema.json: {exc}') from exc
    data = {'$comment': GENERATED, 'schemaVersion': SCHEMA_VERSION}
    # Explicit ordering, including optional interests; never glob content files.
    for section in SECTION_ORDER:
        path = root / 'content' / f'{section}.yaml'
        data[section] = [] if section == 'interests' and not path.exists() else read_yaml(path)
    options = read_yaml(root / 'content' / 'options.yaml')
    validation_errors(data, schema, 'content')
    options_schema = {'$schema': schema['$schema'], '$defs': schema['$defs'], '$ref': '#/$defs/options'}
    validation_errors(options, options_schema, 'content.options')
    for section in ('experience', 'education'):
        for index, entry in enumerate(data[section]):
            if entry['startDate'] and entry['endDate'] and entry['startDate'] > entry['endDate']:
                raise BuildError(f'content.{section}.{index}.endDate: must not precede startDate.')
    ids = [skill['id'] for skill in data['skills']]
    if len(ids) != len(set(ids)):
        raise BuildError('content.skills: skill ids must be unique.')
    return data, options


def render_latex(data, options, root=ROOT):
    env = Environment(loader=FileSystemLoader(root / 'resume' / 'templates'), undefined=StrictUndefined,
                      autoescape=False, keep_trailing_newline=True, trim_blocks=True, lstrip_blocks=True)
    env.filters.update(tex=tex_escape, url=url_escape, keep_words=keep_words, dates=date_range)
    try:
        return env.get_template('cv.tex.j2').render(**data, options=options)
    except (OSError, TemplateError) as exc:
        raise BuildError(f'resume/templates/cv.tex.j2: {exc}') from exc


def atomic_write(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, prefix=f'.{path.name}.', delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(value.encode('utf-8') if isinstance(value, str) else value)
        os.replace(temporary, path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def find_xelatex():
    compiler = shutil.which('xelatex')
    if not compiler and sys.platform == 'darwin':
        candidate = Path('/Library/TeX/texbin/xelatex')
        if candidate.is_file():
            compiler = str(candidate)
    if not compiler:
        raise BuildError('XeLaTeX not found. Install MacTeX (macOS) or MiKTeX (Windows), then restart your terminal/VS Code. See README.md.')
    return compiler


def compile_pdf(root=ROOT):
    compiler = find_xelatex()
    output = root / 'resume' / 'build'
    output.mkdir(parents=True, exist_ok=True)
    pdf = output / 'cv.pdf'
    pdf.unlink(missing_ok=True)  # A stale compiler artifact can never count as success.
    command = [compiler, '-no-shell-escape', '-interaction=nonstopmode', '-halt-on-error',
               '-file-line-error', f'-output-directory={output}', 'cv.tex']
    for pass_number in (1, 2):
        try:
            result = subprocess.run(command, cwd=root / 'resume/output' / 'latex', capture_output=True, text=True,
                                    encoding='utf-8', errors='replace', timeout=180)
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise BuildError(f'XeLaTeX pass {pass_number} failed: {exc}. resume/output/cv.pdf was preserved.') from exc
        if result.returncode:
            tail = '\n'.join((result.stdout + result.stderr).splitlines()[-35:])
            raise BuildError(f'XeLaTeX pass {pass_number} failed; resume/output/cv.pdf was preserved.\n{tail}\nFull log: {output / "cv.log"}')
    if not pdf.is_file() or not pdf.read_bytes().startswith(b'%PDF-'):
        raise BuildError('XeLaTeX produced no valid PDF; resume/output/cv.pdf was preserved.')
    atomic_write(root / 'resume/output' / 'cv.pdf', pdf.read_bytes())


def build(root=ROOT, no_pdf=False, validate_only=False):
    data, options = load_and_validate(root)
    latex = render_latex(data, options, root)
    class_source = root / 'resume' / 'latex' / 'muratcan_cv.cls'
    class_text = '% GENERATED COPY of resume/latex/muratcan_cv.cls. DO NOT EDIT.\n' + class_source.read_text(encoding='utf-8')
    if validate_only:
        print('Content, options, schema, and template are valid.', flush=True)
        return
    output = root / 'resume' / 'build'
    output.mkdir(parents=True, exist_ok=True)
    lock = output / '.resume-build.lock'
    try:
        lock.mkdir()
    except FileExistsError as exc:
        raise BuildError(f'Another build is running. If a previous process crashed, remove {lock}.') from exc
    try:
        atomic_write(root / 'resume/output' / 'resume.json', json.dumps(data, ensure_ascii=False, indent=2) + '\n')
        atomic_write(root / 'resume/output' / 'latex' / 'cv.tex', latex)
        atomic_write(root / 'resume/output' / 'latex' / 'muratcan_cv.cls', class_text)
        if not no_pdf:
            compile_pdf(root)
        print('Generated resume/output/resume.json and resume/output/latex/' + ('.' if no_pdf else '; compiled resume/output/cv.pdf.'), flush=True)
    finally:
        lock.rmdir()


def watched_state(root=ROOT):
    paths = [root / 'content' / f'{section}.yaml' for section in SECTION_ORDER]
    paths += [root / 'content' / 'options.yaml', root / 'resume' / 'resume.schema.json',
              root / 'resume' / 'latex' / 'muratcan_cv.cls', root / 'resume' / 'scripts' / 'build_resume.py']
    paths += sorted(path for path in (root / 'resume' / 'templates').rglob('*') if path.is_file())
    # Read bytes so rapid saves and same-size replacements are detected on all platforms.
    state = []
    for path in paths:
        try:
            state.append((str(path), path.read_bytes()))
        except FileNotFoundError:
            state.append((str(path), None))
    return state


def watch(args):
    print('Watching content, options, schema, template, and class. Press Ctrl+C to stop.', flush=True)
    state = None
    while True:
        current = watched_state()
        if current != state:
            # Wait briefly for editors to finish multi-file/atomic saves.
            time.sleep(0.2)
            state = watched_state()
            try:
                build(no_pdf=args.no_pdf, validate_only=args.validate_only)
            except (BuildError, OSError) as exc:
                print(f'Build error: {exc}', file=sys.stderr, flush=True)
        time.sleep(0.5)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--watch', action='store_true', help='Build now and rebuild when sources change; keep watching after errors.')
    parser.add_argument('--no-pdf', action='store_true', help='Validate and generate JSON/LaTeX without requiring XeLaTeX.')
    parser.add_argument('--validate-only', action='store_true', help='Validate content/options and render template without writing outputs.')
    args = parser.parse_args()
    try:
        watch(args) if args.watch else build(no_pdf=args.no_pdf, validate_only=args.validate_only)
    except KeyboardInterrupt:
        print('\nStopped.', flush=True)
        return 130
    except (BuildError, OSError) as exc:
        print(f'Build error: {exc}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
